<?php

namespace AppBundle\Repository;

/**
 * ColocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColocationRepository extends \Doctrine\ORM\EntityRepository
{
}
