app_colocation:
    resource: "@AppBundle/Resources/config/routing/colocation.yml"
    prefix:   /colocation

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_ecocolocation:
    path:     /ecocolocation
    defaults: { _controller: AppBundle:Default:ecocolocation }