AppBundle\Entity\Colocation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ColocationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            unique: true
        nombrePersonnes:
            type: integer
            nullable: true
        dateCreation:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        jardin:
            type: boolean
            nullable: true
        ressource:
            type: boolean
            nullable: true
        consommation:
            type: boolean
            nullable: true
        alimentation:
            type: boolean
            nullable: true
        espace:
            type: boolean
            nullable: true
        communaute:
            type: boolean
            nullable: true
        quartier:
            type: boolean
            nullable: true
        art:
            type: boolean
            nullable: true
        education:
            type: boolean
            nullable: true
        adresse:
            type: string
            length: 255
            nullable: true
        codePostal:
            type: integer
            nullable: true
        ville:
            type: string
            length: 255
        longitude:
            type: string
            length: 255
            nullable: true
        latitude:
            type: string
            length: 255
            nullable: true
        photo:
            type: text
            nullable: true
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
